# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'FacebookMCA' do
pod 'FBSDKLoginKit', '~> 4.9'
pod 'BMSCore' ,:git =>  'https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-core.git' , :branch => 'mca_team_dev'
pod 'BMSSecurity', :git => 'https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-security.git', :branch => 'mca_team_dev'
end

